### PR TITLE
Deep link ios partial comlpetion, the changes have been made for deep …

### PR DESCRIPTION
**Pull request by ashifkhn**
…linking through xcode for the further implementation of feature a developer account is needed.

https://github.com/Real-Dev-Squad/mobile-app/assets/54736284/b1104c77-5e6b-4670-b353-d54f59a13e2c

### CODE REVIEW

**Comment by shreya-mishra** [comment]
please fix lint issue and merge conflict

**Comment by ashifkhn** [comment]
> please fix lint issue and merge conflict

conflict has been resolved.

**Review by shreya-mishra — COMMENTED** [review]
cant see the video attached

**Comment by ashifkhn** [comment]
> cant see the video attached

Screenshot 2023-10-12 at 8 36 40 PM

**Pull request merged**
