### PR TITLE
Initial project setup

### PR DESCRIPTION
**Pull request by priyanshk20**

### CODE REVIEW

**Comment by shreya-mishra** [comment]
I am not able to find src folder in this branch . I can only see these many files.

**Image :** 
image

**Comment by shreya-mishra** [comment]
If we are using redux then we have redux folder right inside that we have store  middleware , reducer file  isn't it ?

**Comment by priyanshk20** [comment]
> If we are using redux then we have redux folder right inside that we have store middleware , reducer file isn't it ?

@shreya-mishra I think we can add that when we will be initialising redux in our app, thats why I did not add those folders in the starting. Do you want me to?

**Review by shreya-mishra — APPROVED** [review]
Looks fine , merging it into test branch for now !

**Pull request merged**
